

export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_DATA = "SEARCH_DATA";
// async
export const ADD_NEW_SAGA = "ADD_NEW_SAGA";
export const GET_PRODUCTS_SAGA  = "GET_PRODUCTS_SAGA";
export const UPDATE_PRODUCT_SAGA_DATA = "UPDATE_PRODUCT_SAGA_DATA";
export const SEARCH_SAGA_DATA = "SEARCH_SAGA_DATA";
export const DELETE_SAGA_DATA = "DELETE_SAGA_DATA"
